package com.aynvora.core.ai

import com.aynvora.core.result.AynvoraResult

/**
 * Message participant role in AI Assistant conversation.
 */
enum class AiRole {
    USER,
    ASSISTANT,
    SYSTEM,
    TOOL,
}

/**
 * Origin and verified source for information presented by the AI assistant.
 */
data class AiProvenance(
    val sourceDomain: String, // e.g., "ASTROLOGY", "GITA", "GEMSTONE"
    val calculationRulesetOrEdition: String, // e.g. "PARASHARA_CLASSICAL_V1", "GITA_EDITION_1920"
    val verifiedTimestampEpochMs: Long,
    val isRetrievedFact: Boolean = true,
)

/**
 * Structured tool call generated by the on-device AI router.
 */
data class AiToolCall(
    val callId: String,
    val toolName: String,
    val argumentsJson: String,
)

/**
 * Typed execution result returned from a domain tool.
 */
data class AiToolResult(
    val callId: String,
    val toolName: String,
    val resultJson: String,
    val provenance: AiProvenance,
    val isSuccess: Boolean = true,
)

/**
 * Single message within an AI conversation.
 */
data class AiMessage(
    val id: String,
    val role: AiRole,
    val content: String,
    val timestampEpochMs: Long,
    val toolCalls: List<AiToolCall> = emptyList(),
    val toolResults: List<AiToolResult> = emptyList(),
    val provenance: List<AiProvenance> = emptyList(),
)

/**
 * Specification for a domain tool callable by the on-device assistant.
 */
interface AiTool {
    val name: String
    val description: String
    val parametersJsonSchema: String
    suspend fun execute(argumentsJson: String): AynvoraResult<AiToolResult>
}

/**
 * Registry of available structured tools for the AI assistant.
 */
interface AiToolRegistry {
    fun registerTool(tool: AiTool)
    fun getTool(name: String): AiTool?
    fun listTools(): List<AiTool>
}

/**
 * Metadata descriptor for an on-device small language model (e.g. Qwen3-0.6B / 1.7B).
 */
data class AiModelInfo(
    val modelId: String,
    val name: String,
    val parameterCount: String,
    val quantizationFormat: String, // e.g., "Q4_K_M"
    val fileSizeBytes: Long,
    val license: String,
    val isAvailableLocally: Boolean,
)

/**
 * High-level On-Device AI Assistant interface.
 */
interface AiAssistant {
    suspend fun sendMessage(
        conversationId: String,
        userMessage: String,
        tools: List<AiTool> = emptyList(),
    ): AynvoraResult<AiMessage>

    suspend fun getModelInfo(): AiModelInfo
}
