package com.aynvora.core.intelligence

import com.aynvora.core.feature.CoreFeatureId
import com.aynvora.core.garudapuran.GarudaSourceReference
import kotlinx.serialization.Serializable

/**
 * Strict categorizations for evidence items in the prediction/guidance graph.
 * Concrete mathematical facts are never conflated with subjective interpretations.
 */
@Serializable
enum class EvidenceCategory {
    FACT,
    DERIVED_FACT,
    TRADITIONAL_RULE,
    INTERPRETATION,
    USER_CONTEXT,
}

/**
 * Immutable audit provenance for every piece of evidence generated by any feature.
 */
@Serializable
data class EvidenceProvenance(
    val domain: CoreFeatureId,
    val sourceName: String,
    val rulesetOrEdition: String,
    val engineVersion: String,
    val calculationProfile: String? = null,
    val timestampEpochMs: Long,
    val locale: String = "en",
    val timezoneId: String? = null,
    /** Canonical source locator for non-calculation evidence, such as a scripture chapter or verse. */
    val referenceId: String? = null,
    /** Installed, approved content package version; distinct from an engine version. */
    val contentVersion: String? = null,
    /** Typed source-content kind, for example SOURCE_PASSAGE or TRADITIONAL_INTERPRETATION. */
    val contentType: String? = null,
    /** Page-aware source provenance for source-backed Garuda Puran evidence when available. */
    val sourceReference: GarudaSourceReference? = null,
)

/**
 * Individual atomic item of evidence contributing to an answer or guidance output.
 */
@Serializable
data class EvidenceItem(
    val evidenceId: String,
    val domain: CoreFeatureId,
    val category: EvidenceCategory,
    val ruleId: String? = null,
    val summary: String,
    val rawPayloadJson: String? = null,
    val provenance: EvidenceProvenance,
    val priority: Int = 0,
    val conflictStatus: ConflictStatus = ConflictStatus.SUPPORTING,
)

/**
 * Bundle of normalized multi-domain evidence items produced during query evaluation.
 */
@Serializable
data class EvidenceBundle(
    val queryId: String,
    val items: List<EvidenceItem>,
    val contributingDomains: Set<CoreFeatureId>,
    val conflictCount: Int,
    val hasInsufficientData: Boolean,
)

/**
 * Explicit relationship edge in the prediction/guidance graph:
 * Natal factors -> Transit/Dasha -> House/Sign conditions -> Matched Rules -> Exceptions -> Interpretation.
 */
@Serializable
data class EvidenceGraphEdge(
    val sourceEvidenceId: String,
    val targetEvidenceId: String,
    val relationship: String, // e.g. "DERIVES", "APPLIES_RULE", "MODIFIES", "CONTRADICTS"
)

/**
 * Traceable prediction & guidance evidence graph.
 * Guarantees every generated statement answers "Why did this appear?" deterministically.
 */
@Serializable
data class EvidenceGraph(
    val queryId: String,
    val nodes: Map<String, EvidenceItem>,
    val edges: List<EvidenceGraphEdge>,
) {
    /**
     * Finds all contributing factors and rules for a target derived interpretation node.
     */
    fun traceWhy(targetEvidenceId: String): List<EvidenceItem> {
        val directSources = edges
            .filter { it.targetEvidenceId == targetEvidenceId }
            .mapNotNull { nodes[it.sourceEvidenceId] }
        return directSources
    }
}
